import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Check, ChevronDown } from "lucide-react";
import HomeCta from "@/components/HomeCta";

const siteUrl = process.env.NEXTAUTH_URL || "https://scriptgen.learnmade.in";

export const metadata: Metadata = {
  title: "ScriptGen — AI Script Writer & YouTube Script Generator | Free to Start",
  description:
    "ScriptGen is the best AI script writer for YouTube creators. Generate professional video scripts with SEO titles, B-Roll, chapters & Shorts extraction in 4 AI stages. Free to start — English, Tamil, Thanglish, Hindi.",
  alternates: { canonical: siteUrl },
};

const features = [
  ["4-Stage Script Pipeline", "Hook → Content → Outro → Production Notes, generated sequentially for a coherent long-form script."],
  ["Thanglish Engine", "Fine-tune Tamil/English ratio from 10% to 90% to match your channel voice."],
  ["SEO Pack", "AI-generated titles with CTR scores, meta description, and 20+ searchable tags."],
  ["B-Roll & Chapters", "Timestamped B-Roll suggestions and YouTube chapter markers in one pass."],
  ["Shorts Extraction", "Clip-ready viral moments pulled directly from your long-form script."],
  ["AI Image Prompts", "DALL-E–ready visual prompts mapped to your script timeline."],
];

const steps = [
  { n: "01", title: "Hook & Intro", body: "Retention-optimized opening that stops the scroll in the first 30 seconds." },
  { n: "02", title: "Main Content", body: "Structured deep-dive with code explanations, context, and examples." },
  { n: "03", title: "Demo & Outro", body: "Practical walkthrough with a high-conversion call-to-action." },
  { n: "04", title: "Production Notes", body: "B-Roll cues, music mapping, and editing timeline for your editor." },
];

const pricing = [
  { id: "test-drive", label: "Test Drive", tokens: 15, price: 49, approx: "~1 script" },
  { id: "value",   label: "Value",   tokens: 100, price: 199, approx: "~7 scripts", featured: true },
  { id: "creator", label: "Creator", tokens: 500, price: 749, approx: "~35 scripts" },
];

const faqs = [
  {
    q: "What is an AI script writer?",
    a: "An AI script writer is a tool that uses artificial intelligence to automatically generate video scripts for YouTube, social media, ads, and other video content. ScriptGen's AI script writer creates complete, production-ready scripts with hooks, main content, outros, and production notes in under 5 minutes.",
  },
  {
    q: "Is ScriptGen free to use?",
    a: "Yes! ScriptGen gives you 30 free tokens when you sign up — no credit card required. Each token generates one stage of a script. After your free tokens, you can buy token packs starting at ₹49 for 15 tokens (approx. 1 complete script).",
  },
  {
    q: "Which languages does ScriptGen support?",
    a: "ScriptGen supports English, Tamil, Thanglish (Tamil + English mix), and Hindi. The Thanglish engine lets you set a Tamil-to-English ratio, so you can match your exact channel voice — from fully English to fully Tamil and everything in between.",
  },
  {
    q: "How long does it take to generate a YouTube script?",
    a: "ScriptGen generates a complete 4-stage YouTube script in approximately 3–5 minutes. Each stage (Hook & Intro, Main Content, Demo & Outro, Production Notes) is generated sequentially for a coherent, professional result.",
  },
  {
    q: "Does ScriptGen include SEO optimization?",
    a: "Yes. Every script generated by ScriptGen includes an SEO pack with AI-crafted YouTube titles (with CTR scores), meta descriptions, 20+ searchable tags, thumbnail ideas, and pinned comments — everything you need to rank your video.",
  },
  {
    q: "What is Thanglish and why is it useful for YouTube?",
    a: "Thanglish is a blend of Tamil and English commonly spoken and written by Tamil-speaking communities online. Many Tamil YouTube creators use Thanglish because it's relatable and connects better with their audience than pure Tamil or English text. ScriptGen is the only AI script writer with a native Thanglish engine.",
  },
  {
    q: "Can I use ScriptGen for short-form content like YouTube Shorts?",
    a: "Yes. ScriptGen includes automatic Shorts Extraction that identifies viral-worthy moments from your long-form script and formats them as standalone short clips — perfect for YouTube Shorts, Instagram Reels, and TikTok.",
  },
  {
    q: "How is ScriptGen different from ChatGPT for script writing?",
    a: "While ChatGPT can write general scripts, ScriptGen is purpose-built for YouTube. It follows a proven 4-stage pipeline (Hook → Content → Outro → Production Notes), generates SEO-optimized metadata, creates B-Roll suggestions, Shorts clips, chapter timestamps, and AI image prompts — all in one workflow. It also natively supports Thanglish.",
  },
];

export default function HomePage() {
  const jsonLd = [
    {
      "@context": "https://schema.org",
      "@type": "SoftwareApplication",
      "@id": `${siteUrl}/#software`,
      name: "ScriptGen",
      applicationCategory: "BusinessApplication",
      operatingSystem: "Web",
      url: siteUrl,
      description: "AI script writer and YouTube script generator. Generate professional video scripts with SEO, B-Roll, chapters, and Shorts extraction.",
      screenshot: `${siteUrl}/og-scriptgen.png`,
      featureList: [
        "4-Stage AI Script Pipeline",
        "Thanglish Engine",
        "SEO Pack Generator",
        "B-Roll Suggestions",
        "YouTube Shorts Extraction",
        "AI Image Prompts",
        "Multi-language support (English, Tamil, Hindi)",
      ],
      offers: {
        "@type": "AggregateOffer",
        lowPrice: "0",
        highPrice: "749.00",
        priceCurrency: "INR",
        offerCount: "4",
      },
      publisher: { "@id": `${siteUrl}/#organization` },
    },
    {
      "@context": "https://schema.org",
      "@type": "FAQPage",
      mainEntity: faqs.map(({ q, a }) => ({
        "@type": "Question",
        name: q,
        acceptedAnswer: { "@type": "Answer", text: a },
      })),
    },
    {
      "@context": "https://schema.org",
      "@type": "HowTo",
      name: "How to Generate a YouTube Script with ScriptGen AI",
      description: "Generate a complete, production-ready YouTube script using ScriptGen's 4-stage AI pipeline.",
      step: [
        {
          "@type": "HowToStep",
          position: 1,
          name: "Sign in with Google",
          text: "Create a free ScriptGen account using Google Sign-In. You'll receive 30 free tokens instantly — no credit card required.",
        },
        {
          "@type": "HowToStep",
          position: 2,
          name: "Enter your video details",
          text: "Input your video topic, target duration, tone, and select your preferred language (English, Tamil, Thanglish, or Hindi).",
        },
        {
          "@type": "HowToStep",
          position: 3,
          name: "Generate Stage 1: Hook & Intro",
          text: "ScriptGen AI generates a retention-optimized hook and intro that stops viewers from scrolling in the first 30 seconds.",
        },
        {
          "@type": "HowToStep",
          position: 4,
          name: "Generate Stage 2–4",
          text: "Continue through Main Content, Demo & Outro, and Production Notes stages. Each builds on the previous for a coherent script.",
        },
        {
          "@type": "HowToStep",
          position: 5,
          name: "Download and publish",
          text: "Export your complete script with SEO pack, B-Roll suggestions, chapter timestamps, and Shorts clips. Start filming.",
        },
      ],
      totalTime: "PT5M",
      tool: [{ "@type": "HowToTool", name: "ScriptGen AI" }],
      supply: [{ "@type": "HowToSupply", name: "Free ScriptGen account" }],
    },
    {
      "@context": "https://schema.org",
      "@type": "BreadcrumbList",
      itemListElement: [
        { "@type": "ListItem", position: 1, name: "Home", item: siteUrl },
      ],
    },
  ];

  return (
    <main className="pt-14">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />

      {/* ── Hero ─────────────────────────────────────────── */}
      <section className="border-b border-border">
        <div className="mx-auto max-w-screen-xl px-5 py-20 md:py-28">
          <div className="max-w-2xl">
            <p className="mb-3 text-xs font-medium text-muted">AI Script Writer · YouTube Script Generator · Free to Start</p>
            <h1 className="text-3xl font-semibold tracking-tight text-white sm:text-4xl md:text-5xl">
              The best AI script writer<br />for YouTube creators.
            </h1>
            <p className="mt-4 max-w-lg text-sm leading-relaxed text-muted">
              ScriptGen generates production-ready YouTube scripts in 4 sequential AI stages — Hook, Content, Outro, and Production Notes. Built natively for Tamil and Thanglish creators, supporting English, Tamil, Hindi, and Thanglish.
            </p>
            <div className="mt-8 flex flex-wrap gap-3">
              <HomeCta className="inline-flex items-center gap-2 rounded bg-accent px-4 py-2 text-sm font-medium text-white transition hover:bg-accent/90">
                Start Free — No Card Needed
                <ArrowRight className="h-3.5 w-3.5" />
              </HomeCta>
              <Link
                href="#how-it-works"
                className="inline-flex items-center gap-2 rounded border border-border px-4 py-2 text-sm font-medium text-muted transition hover:border-border2 hover:text-white"
              >
                See how it works
              </Link>
            </div>
            <p className="mt-3 text-xs text-hint">Free to start — 30 tokens on signup, no credit card required.</p>
          </div>
        </div>
      </section>

      {/* ── Trust bar ─────────────────────────────────────── */}
      <section className="border-b border-border">
        <div className="mx-auto max-w-screen-xl px-5 py-5">
          <div className="flex flex-wrap items-center gap-x-8 gap-y-2 text-xs text-muted">
            <span className="flex items-center gap-1.5"><Check className="h-3.5 w-3.5 text-accent2" /> Free 30 tokens on signup</span>
            <span className="flex items-center gap-1.5"><Check className="h-3.5 w-3.5 text-accent2" /> No credit card required</span>
            <span className="flex items-center gap-1.5"><Check className="h-3.5 w-3.5 text-accent2" /> English, Tamil, Thanglish, Hindi</span>
            <span className="flex items-center gap-1.5"><Check className="h-3.5 w-3.5 text-accent2" /> SEO pack included</span>
            <span className="flex items-center gap-1.5"><Check className="h-3.5 w-3.5 text-accent2" /> B-Roll + Shorts extraction</span>
          </div>
        </div>
      </section>

      {/* ── How it works ─────────────────────────────────── */}
      <section id="how-it-works" className="border-b border-border">
        <div className="mx-auto max-w-screen-xl px-5 py-16">
          <p className="mb-2 text-xs font-medium uppercase tracking-widest text-muted">How It Works</p>
          <h2 className="mb-8 text-xl font-semibold text-white">Generate a full YouTube script in 4 AI stages</h2>
          <div className="grid gap-px border border-border bg-border sm:grid-cols-2 lg:grid-cols-4">
            {steps.map((step) => (
              <div key={step.n} className="bg-bg px-6 py-7">
                <span className="text-xs font-mono font-medium text-accent2">{step.n}</span>
                <h3 className="mt-3 text-sm font-semibold text-white">{step.title}</h3>
                <p className="mt-2 text-xs leading-relaxed text-muted">{step.body}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Features ─────────────────────────────────────── */}
      <section className="border-b border-border">
        <div className="mx-auto max-w-screen-xl px-5 py-16">
          <p className="mb-2 text-xs font-medium uppercase tracking-widest text-muted">Features</p>
          <h2 className="mb-8 text-xl font-semibold text-white">Everything a YouTube script writer needs</h2>
          <div className="grid gap-px border border-border bg-border sm:grid-cols-2 lg:grid-cols-3">
            {features.map(([title, body]) => (
              <div key={title} className="bg-bg px-6 py-6">
                <div className="flex items-start gap-3">
                  <Check className="mt-0.5 h-3.5 w-3.5 shrink-0 text-accent2" />
                  <div>
                    <p className="text-sm font-medium text-white">{title}</p>
                    <p className="mt-1.5 text-xs leading-relaxed text-muted">{body}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Language support ─────────────────────────────── */}
      <section className="border-b border-border">
        <div className="mx-auto max-w-screen-xl px-5 py-16">
          <p className="mb-4 text-xs font-medium uppercase tracking-widest text-muted">Language Support</p>
          <h2 className="mb-8 text-xl font-semibold text-white">Built for regional creators</h2>
          <div className="flex flex-wrap gap-2">
            {[
              { label: "English",          active: false },
              { label: "Hindi / Hinglish", active: false },
              { label: "Tamil",            active: false },
              { label: "Thanglish",        active: true  },
            ].map(({ label, active }) => (
              <span
                key={label}
                className={`rounded border px-3 py-1.5 text-xs font-medium ${
                  active
                    ? "border-accent/30 bg-accent/10 text-accent2"
                    : "border-border bg-surface text-muted"
                }`}
              >
                {label}
              </span>
            ))}
          </div>
          <p className="mt-4 text-xs text-hint">
            Thanglish mode lets you set a Tamil/English ratio — from code-heavy English to full Tamil, with everything in between.
          </p>
        </div>
      </section>

      {/* ── Pricing ──────────────────────────────────────── */}
      <section id="pricing" className="border-b border-border">
        <div className="mx-auto max-w-screen-xl px-5 py-16">
          <p className="mb-4 text-xs font-medium uppercase tracking-widest text-muted">Pricing</p>
          <h2 className="mb-2 text-xl font-semibold text-white">Pay once, use anytime</h2>
          <p className="mb-10 text-sm text-muted">No subscription. Tokens never expire. All prices in INR.</p>

          <div className="grid max-w-3xl gap-4 sm:grid-cols-3">
            {pricing.map((tier) => (
              <div
                key={tier.id}
                className={`rounded border p-5 ${
                  tier.featured
                    ? "border-accent/50 bg-accent/5"
                    : "border-border bg-surface"
                }`}
              >
                {tier.featured && (
                  <p className="mb-3 w-fit rounded bg-accent/20 px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide text-accent2">
                    Best Value
                  </p>
                )}
                <p className="text-xs text-muted">{tier.label}</p>
                <p className="mt-2 text-3xl font-bold text-white">{tier.tokens}</p>
                <p className="text-xs text-muted">tokens · {tier.approx}</p>
                <p className="mt-4 text-lg font-semibold text-white">₹{tier.price}</p>
                <Link
                  href="/tokens"
                  className={`mt-4 block rounded border py-2 text-center text-xs font-medium transition ${
                    tier.featured
                      ? "border-accent bg-accent text-white hover:bg-accent/90"
                      : "border-border text-muted hover:border-border2 hover:text-white"
                  }`}
                >
                  Get started
                </Link>
              </div>
            ))}
          </div>
          <p className="mt-5 text-xs text-hint">All prices in INR including GST · Secured by Razorpay</p>
        </div>
      </section>

      {/* ── Internal links ────────────────────────────────── */}
      <section className="border-b border-border">
        <div className="mx-auto max-w-screen-xl px-5 py-12">
          <p className="mb-6 text-xs font-medium uppercase tracking-widest text-muted">Resources & Tools</p>
          <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
            {[
              { href: "/youtube-script-writer", label: "YouTube Script Writer", desc: "Dedicated script writing for YouTube videos" },
              { href: "/ai-script-writer", label: "AI Script Writer", desc: "Automated AI-powered script writing" },
              { href: "/free-script-generator", label: "Free Script Generator", desc: "Generate scripts free — no credit card" },
              { href: "/script-writer-online", label: "Script Writer Online", desc: "Write scripts in your browser instantly" },
            ].map((link) => (
              <Link
                key={link.href}
                href={link.href}
                className="flex flex-col rounded border border-border bg-surface px-4 py-4 text-sm transition hover:border-border2"
              >
                <span className="font-medium text-white">{link.label}</span>
                <span className="mt-1 text-xs text-muted">{link.desc}</span>
              </Link>
            ))}
          </div>
        </div>
      </section>

      {/* ── FAQ ──────────────────────────────────────────── */}
      <section id="faq" className="border-b border-border">
        <div className="mx-auto max-w-screen-xl px-5 py-16">
          <p className="mb-4 text-xs font-medium uppercase tracking-widest text-muted">FAQ</p>
          <h2 className="mb-10 text-xl font-semibold text-white">Frequently asked questions about AI script writing</h2>
          <div className="grid max-w-3xl gap-px border border-border bg-border">
            {faqs.map(({ q, a }) => (
              <details key={q} className="group bg-bg">
                <summary className="flex cursor-pointer items-center justify-between gap-4 px-6 py-5 text-sm font-medium text-white marker:hidden list-none">
                  <span>{q}</span>
                  <ChevronDown className="h-4 w-4 shrink-0 text-muted transition-transform group-open:rotate-180" />
                </summary>
                <p className="px-6 pb-5 text-xs leading-relaxed text-muted">{a}</p>
              </details>
            ))}
          </div>
        </div>
      </section>

      {/* ── CTA ──────────────────────────────────────────── */}
      <section>
        <div className="mx-auto max-w-screen-xl px-5 py-16">
          <div className="flex flex-col items-start justify-between gap-6 rounded border border-border bg-surface p-8 sm:flex-row sm:items-center">
            <div>
              <h2 className="text-lg font-semibold text-white">Ready to write your next YouTube script with AI?</h2>
              <p className="mt-1 text-sm text-muted">Start with 30 free tokens. No credit card required. Supports English, Tamil, Thanglish, Hindi.</p>
            </div>
            <HomeCta className="inline-flex shrink-0 items-center gap-2 rounded bg-accent px-4 py-2 text-sm font-medium text-white transition hover:bg-accent/90">
              Start Free <ArrowRight className="h-3.5 w-3.5" />
            </HomeCta>
          </div>
        </div>
      </section>

    </main>
  );
}
